#ifndef TENSORFLOW_LITE_VERSION_H_
#define TENSORFLOW_LITE_VERSION_H_

#define TFLITE_VERSION_MAJOR 2
#define TFLITE_VERSION_MINOR 6
#define TFLITE_VERSION_PATCH 0

#endif  // TENSORFLOW_LITE_VERSION_H_
